### ISSUE TITLE
[Docs] Note in docs if Magnus requires Expo?

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [jsartisan/react-native-magnus#89]
## Documentation Link

https://magnus-ui.com/docs/
https://magnus-ui.com/docs/button/

## Describe the problem

In trying to use Magnus UI for the first time in a React Native app that does not include Expo, Input, Div, Text, etc. all seem to work without error. The problem I have is with `Button`.

Button complains that the children are undefined despite trying both `<Button>some text</Button>` and `<Button><Text>some text</Text></Button>`

## Describe the improvement

If this error I'm seeing is a result of not including Expo in my project, perhaps you could note that on the documentation Introduction page and/or the Button documentation page?

**Comment by wadewadewadewadewadewade** [comment]
I figured out what the problem was: `Pressable` was only introduced into React in 0.63, and I was using 0.62.

Upgrading the version of React I was using to 0.64 solved my issue (I assume 0.63 would have also solved my issue)

**Comment by jsartisan** [comment]
@wadewadewadewadewadewade This info is present on the button page of docs - https://magnus-ui.com/docs/button/

_Button won’t work with Expo versions < 38. This is because we moved to Pressable component and Pressable is not available in Expo in version < 38. So we recommend using magnus version < 1.0.40 for expo versions < 38._
